spring:
  application:
    name: order-service
  config:
      import: optional:configserver:http://config-server:8888




#spring.h2.console.enabled=true
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.hibernate.ddl-auto=create

#spring.application.name=order-service
#server.port=8083
#spring.datasource.url=jdbc:postgresql://localhost:5432/order
#spring.datasource.username=awais
#spring.datasource.password=awais
#spring.jpa.database=postgresql
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect