#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: http://localhost:8081
#          # uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/products/**
#          filters:
#            - "RewritePath=/products(?<segment>/?.*), /api/products${segment}"
#        - id: user-service
#          uri: http://localhost:8082
##          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - "RewritePath=/users(?<segment>/?.*), /api/users${segment}"
#        - id: order-service
#          uri: http://localhost:8083
#          #uri: lb:ORDER-SERVICE
#          predicates:
#            - Path=/orders/**, /cart/**
#          filters:
#            - "RewritePath=/(?<segment>/?.*), /api/{segment}"
#        - id: eureka-server
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - SetPath=/
#        - id: eureka-server-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**
#
#server:
#  port: 8080

#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}


resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

# SECURITY
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8554/realms/ecom-app
          jwk-set-uri: http://keycloak:8080/realms/ecom-app/protocol/openid-connect/certs


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

