server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: awais
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.1.100}  # Replace with actual RabbitMQ server IP or hostname
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}   # default vhost is "/"
    connection-timeout: 30000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

app:
  message: "Hello order"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log   # Log file path + name
  logback:
    rollingpolicy:
      max-file-size: 5MB   # Ek file ka max size (uske baad nayi file banegi)
      max-history: 7       # Purani files 7 tak rakhi jayengi, uske baad delete ho jayengi



#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#mysql query conn...
#spring.datasource.url=jdbc:mysql://localhost:3306/productservice
#query show
#spring.jpa.properties.hibernate.format_sql=true

#post sql
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_tc0p4AxJXEvs

#spring.application.name=product-service
#server.port=8081
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/product
#spring.datasource.username=awais
#spring.datasource.password=awais
#spring.jpa.database=postgresql
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#server:
#  port: 8081
#spring:
#  datasource:
#    password: ${DB_USER}
#    url: jdbc:postgresql://localhost:5432/product
#    username: ${DB_PASSWORD}
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#app:
#  message: "Hello product"