server:
  port: 8082
spring:
  data:
    mongodb:
      database: userdb
      uri: ${MONGO_URI}
    rabbitmq:
      host: ${RABBITMQ_HOST:192.168.1.100}  # Replace with actual RabbitMQ server IP or hostname
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USERNAME:guest}
      password: ${RABBITMQ_PASSWORD:guest}
      virtual-host: ${RABBITMQ_VHOST:guest}   # default vhost is "/"
      connection-timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


logging:
  file:
    name: logs/${spring.application.name}.log   # Log file path + name
  logback:
    rollingpolicy:
      max-file-size: 5MB   # Ek file ka max size (uske baad nayi file banegi)
      max-history: 7       # Purani files 7 tak rakhi jayengi, uske baad delete ho jayengi

#keyclock


keycloak:
  admin:
    username: user
    password: Awais12@#
    server:
      url: http://keycloak:8080
    realm: ecom-app
    client-id: oauth2-pkce
    client-uid: 224a6b05-6d50-4061-9360-d74644971af0


#postsql
#spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
#spring.datasource.username=awais
#spring.datasource.password=Awais12@$
#spring.jpa.database=postgresql
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#h2
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create

#spring.application.name=user-service
#server.port=8082
#spring.data.mongodb.uri=mongodb://localhost:27017/userdb
#spring.data.mongodb.database=userdb